# Generated by Django 3.0.1 on 2019-12-24 22:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Fart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(blank=True, default='Flavor Town', null=True)),
                ('state', models.TextField(blank=True, default='BFE', null=True)),
                ('score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('noise_scale', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('smell_scale', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('exposures', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)])),
                ('date_farted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('ftype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fartType', to='fart.FartType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
